- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/ibm-monitoring-prometheus-operator-ext.v1.8.0.clusterserviceversion.yaml
> remove replace packge in csv

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.1/ibm-monitoring-prometheus-operator-ext.v1.8.1.clusterserviceversion.yaml
- pkg/controller/prometheusext/model/constants.go
> add dependency request and add healthcheck dependency annotation

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
> promote 1.9.1 beta to stable-v1

- Makefile
- common/scripts/config_docker.sh
> push to artifactory

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.2/ibm-monitoring-prometheus-operator-ext.v1.9.2.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.2/monitoring.operator.ibm.com_prometheusexts_crd.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
- version/version.go
> add beta/dev channel 1.9.2

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.2/ibm-monitoring-prometheus-operator-ext.v1.9.2.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/controller/prometheusext/model/common.go
> remove product version

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.2/ibm-monitoring-prometheus-operator-ext.v1.9.2.clusterserviceversion.yaml
- deploy/operator.yaml
> update operands images

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.2/ibm-monitoring-prometheus-operator-ext.v1.9.2.clusterserviceversion.yaml
- deploy/operator.yaml
> fix wrong prometheus image SHA

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.2/ibm-monitoring-prometheus-operator-ext.v1.9.2.clusterserviceversion.yaml
- deploy/operator.yaml
> enable operator for multiple architectures and operating systems

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.3/ibm-monitoring-prometheus-operator-ext.v1.9.3.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.3/monitoring.operator.ibm.com_prometheusexts_crd.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
- deploy/operator.yaml
- version/version.go
> update base images of prometheus controller and prometheus operator

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.3/ibm-monitoring-prometheus-operator-ext.v1.9.3.clusterserviceversion.yaml
- deploy/operator.yaml
> update base image and rebuild

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.4/ibm-monitoring-prometheus-operator-ext.v1.9.4.clusterserviceversion.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- pkg/controller/prometheusext/model/scc.go
- pkg/controller/prometheusext/reconsiler/reconsiler.go
SCC should be used after creation.
> fix scc issue

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/ibm-monitoring-prometheus-operator-ext.v1.9.6.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/monitoring.operator.ibm.com_prometheusexts_crd.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
- version/version.go
> create v3 channel and bump the version

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/ibm-monitoring-prometheus-operator-ext.v1.10.0.clusterserviceversion.yaml
- deploy/operator.yaml
> update images except initcontainer and ingress

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/ibm-monitoring-prometheus-operator-ext.v1.10.0.clusterserviceversion.yaml
- deploy/operator.yaml
> fix config reload issue and update initcontainer image

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/ibm-monitoring-prometheus-operator-ext.v1.10.0.clusterserviceversion.yaml
- deploy/operator.yaml
> update prometheus controller for protobuf issue

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/ibm-monitoring-prometheus-operator-ext.v1.9.6.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45738
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45762
> 2.5.11 version of icp-management-ingress digest updated

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/ibm-monitoring-prometheus-operator-ext.v1.9.6.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46137
> refresh ingress digest

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.11.0/ibm-monitoring-prometheus-operator-ext.v1.11.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.11.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46533
> operand auto sha update+bump version

- Makefile
- pkg/controller/prometheusext/prometheusext_controller.go
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45123
> Copyright year updated #45123

- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.17.0/ibm-monitoring-prometheus-operator-ext.v1.17.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.17.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
- deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50617
> version bump for CS 3.14.0

- pkg/controller/prometheusext/model/router.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50646
> Router container liveness/readiness probe timeout introduced for prometheus
